# These are supported funding model platforms
custom: ['https://www.paypal.com/paypalme/bkafesit'] 

# USDT (TRC20): TWrhjNrdS4uZPzEvtsiQWKRVEKTgfoMMoq
# BTC: bc1qx8nfxs7ce0z5cdgh4xpguk77eu4ujadns6fr4u
